name: PIPELINE-CI-CD

on:
  push:
    branches: ["master"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4.2.2

      - name: Docker Login
      - uses: docker/login-action@v3.4.0
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      
      - name: Build da imagem
      - uses: docker/build-push-action@v6.15.0
        with: 
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags: |
            dfernandesapoioprodesp/nota-barueri-api:v1
            dfernandesapoioprodesp/nota-barueri-api:latest
