name: PIPELINE-CI-CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build da imagem
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            dfernandesapoioprodesp/nota-barueri-api:v${{github.run.number}}
            dfernandesapoioprodesp/nota-barueri-api:latest
<<<<<<< HEAD
<<<<<<< HEAD
  
=======
        
>>>>>>> cda2d262327d6263b0c2af38e6cc5a02159f4181
=======
        
>>>>>>> cda2d262327d6263b0c2af38e6cc5a02159f4181
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
          install_components: kubectl

      - name: Validate Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

<<<<<<< HEAD
<<<<<<< HEAD
 #     - name: Update Image in Manifest
 #       run: |
 #         sed -i "s|IMAGE_TAG|${{ github.run.number }}|g" k8s/deployment.yaml
=======
  #    - name: Update Image in Manifest
  #      run: |
  #        sed -i "s|IMAGE_TAG|${{ github.run.number }}|g" k8s/deployment.yaml
>>>>>>> cda2d262327d6263b0c2af38e6cc5a02159f4181
=======
  #    - name: Update Image in Manifest
  #      run: |
  #        sed -i "s|IMAGE_TAG|${{ github.run.number }}|g" k8s/deployment.yaml
>>>>>>> cda2d262327d6263b0c2af38e6cc5a02159f4181

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
