name: PIPELINE-CI-CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build da imagem
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            dfernandesapoioprodesp/nota-barueri-api:v${{github.run.number}}
            dfernandesapoioprodesp/nota-barueri-api:latest
  
#  CD:
#    runs-on: ubuntu-latest
#    needs: [CI]
#
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v3
#
#      - name: Contexto do kubernetes
#        uses: Azure/k8s-set-context@v3.0
#        with: 
#          method: kubeconfig
#          kubeconfig: ${{secrets.K8S_KUBECONFIG}}
#
#      - name: Deploy
#        uses: Azure/k8s-deploy@v4.9
#        with:
#          images: dfernandesapoioprodesp/nota-barueri-api:v${{github.run.number}}
#          manifests: |
#            k8s/deployment.yaml
      
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          export_default_credentials: true
          install_components: kubectl

      - name: Validate Authentication
        run: |
          gcloud auth list
          gcloud config list

      - name: Get GKE Cluster Credentials
        run: |
          gcloud container clusters get-credentials ${{ secrets.GKE_CLUSTER_NAME }} --region ${{ secrets.GKE_REGION }}

      - name: Update Image in Manifest
        run: |
          sed -i "s|IMAGE_TAG|${{ github.run.number }}|g" k8s/deployment.yaml

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v4
        with:
          manifests: |
            k8s/deployment.yaml
            k8s/service.yaml
          images: |
            dfernandesapoioprodesp/nota-barueri-api:v${{ github.run.number }}
          namespace: default
