name: PIPELINE-CI-CD

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build da imagem
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: |
            dfernandesapoioprodesp/nota-barueri-api:v${{github.run.number}}
            dfernandesapoioprodesp/nota-barueri-api:latest
  
  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Contexto do kubernetes
        uses: Azure/k8s-set-context@v3.0
        with: 
          method: kubeconfig
          kubeconfig: ${{secrets.K8S_KUBECONFIG}}

#      - name: Deploy
#        uses: Azure/k8s-deploy@v4.9
#        with:
#          images: dfernandesapoioprodesp/nota-barueri-api:v${{github.run.number}}
#          manifests: |
#            k8s/deployment.yaml
      
